FROM node:24.15.0-alpine3.22 AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY package.json ./
COPY esbuild.config.mjs ./
COPY src ./src

RUN pnpm install --prod --ignore-scripts

RUN npx esbuild --bundle --platform=node --format=esm --outdir=dist src/index.ts

FROM node:24.15.0-alpine3.22

WORKDIR /app

COPY --from=builder /app/dist/index.js ./index.js

EXPOSE 3000

CMD ["node", "index.js"]